version: '3'
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=30d'
    ports:
      - "9090:9090"
    restart: on-failure
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter-linux-armv7
    ports:
      - "9100:9100"
    restart: on-failure
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    restart: on-failure
  inet-mon:
    container_name: inet-mon
    build: .
    env_file:
      - .env
    ports:
      - "9000:9000"
volumes:
  prometheus_data: {}
  grafana_data: {}
  dhparam_cache: {}
